# Component of GAE Project for TMSCA Contest Automation
# Copyright (C) 2015 Sushain Cherivirala
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see [http://www.gnu.org/licenses/].

application: villagetmsca
version: 8-2-0
runtime: java
threadsafe: false
sessions_enabled: true

handlers:
- url: /index.html
  servlet: contestWebsite.MainPage

- url: /about
  servlet: contestWebsite.About

- url: /registration
  servlet: contestWebsite.Registration

- url: /login
  servlet: contestWebsite.Login

- url: /directions
  servlet: contestWebsite.Directions

- url: /signout
  servlet: contestWebsite.Logout

- url: /createAdmin
  login: admin
  servlet: contestWebsite.CreateAdmin

- url: /adminPanel
  servlet: contestWebsite.AdminPanel

- url: /data/*
  servlet: contestWebsite.Data

- url: /contactUs
  servlet: contestWebsite.ContactUs

- url: /schoolScores
  servlet: contestWebsite.SchoolScores

- url: /contestResults
  servlet: contestWebsite.PublicResults

- url: /editRegistration
  servlet: contestWebsite.EditRegistration

- url: /forgotPass
  servlet: contestWebsite.ForgotPassword
  
- url: /changePass
  servlet: contestWebsite.ChangePassword

- url: /tabulate
  login: admin
  servlet: contestTabulation.Main

- url: /createSpreadsheet
  servlet: contestTabulation.Setup

- url: /authToken
  servlet: contestWebsite.OAuth

- url: /clearScores
  servlet: contestWebsite.ClearScores

- url: /400
  servlet: errors.BadRequest_400

- url: /401
  servlet: errors.Unauthorized_401

- url: /403
  servlet: errors.Prohibited_403

- url: /404
  servlet: errors.NotFound_404

- url: /500
  servlet: errors.ServerError_500

static_files:
  - include: /favicon.ico
    expiration: 14d
  - include: /css/**.css
    expiration: 7d
  - include: /js/**.js
    expiration: 7d
  - include: /img/**
    expiration: 7d
  - include: /robots.txt
    expiration: 7d
  - include: /fonts/**
    expiration: 28d
  - include: /misc/**
    expiration: 28d

resource_files:
  - include: /html/**.html

web_xml: |
  <error-page>
    <error-code>400</error-code>
    <location>/400</location>
  </error-page>
  <error-page>
    <error-code>401</error-code>
    <location>/401</location>
  </error-page>
  <error-page>
    <error-code>403</error-code>
    <location>/403</location>
  </error-page>
  <error-page>
    <error-code>404</error-code>
    <location>/404</location>
  </error-page>
  <error-page>
    <error-code>500</error-code>
    <location>/500</location>
  </error-page>
